import { Station } from '../components/forensic/types';

export function generatePDFReport(station: Station) {
  const reportContent = `
ECO-SENTINEL ENVIRONMENTAL ENFORCEMENT REPORT
═══════════════════════════════════════════════════════════════

INCIDENT CLASSIFICATION: ${station.status}
REPORT GENERATED: ${new Date().toLocaleString('en-US', { timeZone: 'UTC' })} UTC
CASE ID: ECO-${Date.now()}

───────────────────────────────────────────────────────────────
STATION IDENTIFICATION
───────────────────────────────────────────────────────────────
Name: ${station.name}
Location: ${station.lat.toFixed(4)}°N, ${station.lng.toFixed(4)}°E
Data Source: ${station.source}
Status: ${station.status}

───────────────────────────────────────────────────────────────
POLLUTION METRICS
───────────────────────────────────────────────────────────────
PM2.5 Concentration: ${station.pm25.toFixed(1)} µg/m³
Z-Score Anomaly: ${station.zscore.toFixed(2)}σ
Threshold Exceedance: ${station.pm25 > 100 ? 'YES - CRITICAL' : station.pm25 > 55 ? 'YES - WARNING' : 'NO'}

───────────────────────────────────────────────────────────────
FORENSIC ANALYSIS
───────────────────────────────────────────────────────────────
Source Confidence: ${station.status === 'CRITICAL' ? '89%' : station.status === 'WARNING' ? '71%' : '42%'}

Evidence Chain:
  ✓ Wind Trajectory: ${station.status !== 'NORMAL' ? 'WITHIN 5km UPWIND' : 'NO MATCH'}
  ✓ Satellite Match: ${station.status === 'CRITICAL' ? 'SPECTRAL CONFIRMED' : 'HEURISTIC FALLBACK'}
  ✓ Concentration: ${station.pm25.toFixed(1)} µg/m³
  ✓ Z-Score Anomaly: ${station.zscore.toFixed(1)}σ

${
  station.status !== 'NORMAL'
    ? `───────────────────────────────────────────────────────────────
ATTRIBUTED SOURCE
───────────────────────────────────────────────────────────────
Industrial Zone: PATANCHERU INDUSTRIAL
Coordinates: 17.530°N, 78.199°E
Distance: 4.8km UPWIND
Wind Direction: 315° NW
Wind Speed: 3.2 m/s
Atmospheric Stability: Pasquill Class D

───────────────────────────────────────────────────────────────
RECOMMENDED ACTIONS
───────────────────────────────────────────────────────────────
1. IMMEDIATE INSPECTION of Patancheru Industrial Zone
2. VERIFY industrial operations and emission controls
3. COLLECT on-site samples for laboratory analysis
4. REVIEW facility compliance records
5. ISSUE NOTICE if violations confirmed

───────────────────────────────────────────────────────────────
LEGAL AUTHORITY
───────────────────────────────────────────────────────────────
Air (Prevention and Control of Pollution) Act, 1981
Environment (Protection) Act, 1986
National Ambient Air Quality Standards (NAAQS)
`
    : ''
}
───────────────────────────────────────────────────────────────
REPORT METADATA
───────────────────────────────────────────────────────────────
Generated By: ECO-SENTINEL AI Forensics System
Report Type: Automated Environmental Incident Report
Jurisdiction: Telangana Pollution Control Board
Contact: enforcement@eco-sentinel.gov.in

═══════════════════════════════════════════════════════════════
END OF REPORT
═══════════════════════════════════════════════════════════════
`;

  // Create and download as text file (PDF generation would require a library)
  const blob = new Blob([reportContent], { type: 'text/plain' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = `ECO-SENTINEL-REPORT-${station.id}-${Date.now()}.txt`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}
